apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flask-creds
  namespace: projectblr
spec:
  encryptedData:
    key1: AgApNM01Oz3pvu1STHiZwC+O7t/9dFJbkHaphhaLJyKZA6GVVp81lg/UWmoYorR+YG2+qtBpaUtdpwNbTn+E84oakP8G4DvPkVomTLajguzMfuZ8dC3W7GPBV3XAGCzRdir/GeghdHb++lVqZj+dSg2kBx15EVlQCQwCYZs4UOFV7ZGtVsbESXgMv9Qp1TXPFgIkV/iQRNiPDOxRCBY2mQ09UeWbDgi3oKb9ieQsz47iPHf0si/GWLfkwPWBC0yAgtXZjXetmlRty+UN4kmsnqEcZhUqD7N84sj1Z4hrnTOeKGq/Uv8lN+DlawJ9mmcT9F2fpuGIrVSlesSaV2+j2EzeN6vTaLpopldi90fTgvaXkQVur3LkELjWLeGv35TKduLuYv9Fdrtkd67aVHJYGJT8s/Dct02GM21WG+jLxlxnMCTozon9+HaXmHwHZRoaRjiAtYi+KUAFVQLSoszqZczyhjEXIBTWJnKsmWeRoN83t1fpThwwZoq0Yc3q205xJp4S9Nne09PqGepgr9nzQ92CMDO3TgapBemoZOI2/HcavaWqsc84aaJyf+sMGdDQchywTmMGFAaOBIJ1sktjGvhClSmbfb5Sarm8uist06eYJabZPQnzrYpQYaqfv7I8sMtojvyxo68VlwO7xCCYvafTRRrWS+BGHBT2Blwk5f2F8U/0g8jBZY52RfqL7ioSDMLoE4fE2GwQD+MLOs5z
    key2: AgC/lOeSMhfrCg3mN5iKRlkL+dDuZPvLthrV863zRrwEloXRrZpxWmH+5OMAKIRq/GYxOPJZ75gxMKvNtBEFrOw1XQP1zNSCa3FyDS6bP6ngmZpEC4nYx0v9njlV2UMMrdBLALXPX5/AeKdwX+Fd4Wk6XFhnX2jdU/7reJMHeHdlIV8U9XGMMLXOk5YtgDTpkP5M1G/+cbFXrKPIUzA2CqUYINz6bfsiA7PMkvmFW8i9b1/pcGv9bRI4OGkkGMFbUHdz8gdT027fPBZtLSZ1zSIMnRaTt/dqbe9eaWLRdydOw7xEqjOmc3K4JC7o4/VkmAsm/EoKrlZHmOsCN9+4k9+PLASU1nXat+WpzfBrbHkSqi+9uUnRvg21MPPu6vzNryD0J+Trx1RFzPVprLl+h55uXpohumgAsRaTjpGmMEjfKu1kMeJFDcNCdbzPUA0E/YtvV24J6I6i7pxv/R3k02PC5oCpCRVvcwPis5l6xnAF9fqGrd+hWppKA7WTeaMKlyuyZfvrO6zCjJoSCjZQtDY5NIARLJVsbDB3TFlWZy8lZD2DgX0yUG9gesPcajjMxDdUUDytBqMTLIO4Dw3OKLrvStfYQ8zvZUtsFTlay2ExwAYzyFqFsjex6dU8g0DIqhhUMhv3N3eCahILi1zkaQ8iXBC0Sh55FVt38qfhYxE2IzPX6A+TRMMk0XA1egT4PwxG9i513uZfMC1Tyg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: flask-creds
      namespace: projectblr

