apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flask-creds
  namespace: projectblr
spec:
  encryptedData:
    key1: AgA+KqUs3ugD/lrJl6HugoELGNDxSO84Bnbp1F3E27cMSwbjsbNLpubZFDeHVH08hVWZEwmDG3tv2/KPx7sbOnaTe/c/qqDj0yIE/ItGCNG8Xpz8qj3BWrYb0A44rp+zmu9MLpYcRMyacSB1olzEedPP6T34o6KXf8K44Ob649nr1ZI0LSwt9ZvwSVFSTZspHzARwRzjK2sxekXJPFjnQT2wOZkNDlBF5sX8W6lRK/kmwx5LGfnMEiXhr6Q9/mSKyJZltJuxTIE9VcTqDQH60YT0rgRM4rTfwCTqgjKGhT+mKtvfdgYA2aKqfwyoEij2fJ+Nx7AGmazHGuEIjlbJrKMY2eIwAwp4qK0Js3AYXzCbQ1PG71bbyVj50TsRjCS23ht6tJGDsHTfzAYlmSUbMHhGyenUsJuXS/minAHS3kW+frHkGYlV0pDAyH5r8SlWX46+5nKOmLj39Bd9Ur29mGr4dmTol0KzE3alN2qKvdKCkjy3gHt8YbUz5JIdP+AGBz2QzKqXrVwLpDCErwCNf7fZMFUpSXkMJsFqQS4S7yC0iuRFiwlLWqham6/FGsYheeX2D54uqxtZOfi3l0vZjvSaCYeGFiaTz9xqFa51nohqQ7hV/o3fJWhUd6xUrurAdj8He6yNcvH7JJyKZQK/yJn9srg91PP0OegkgnMBSHq8rf1WfM864oqXLf80mf4z9aww6aUHnlZ2dannmQ==
    key2: AgBnhVOwHoRDD9w1nLy7F3Kry3tlZIpjiTgMFvM/kpzHAk9taMYS1XH3R8wQUTaGfQgB44a7qGTEt3gHlHcFfyLvlwg+BLtk+pcqKHFNyCqgPuQRYP0bXdkZeC5mf/+dvwo+oPjTLr5mUMZ4O5Z1K8JwQYze/YoSeKa6+cVy7M4zlw6CrHVFLZzwWs+DpPOhnexxARHVMBtiRsWaLhgRvlwJXj+JO5/gRAOPxyZ2VRCv3u/M1P4+Neo7taPFA4a8i+qX23f7ie2hB6Wpe3TbWI7HZUI4KvoP+61f2EgQFtVN5ThUyQ3/6j6B5gcBRNunqB8uc3uXCRo+ZmP2qrHAbF+yGTYAwm6af9n6z5YFZiFTwIh49X5Yj0IYmuVfhrZECev2IlHvFCeERdkk3bO9JS6LPKSSpKFP2YRQw3vqDtp84vskROM9QXjWWwkQO9P7Hr7CYQzGMzQGW8DxjNkvz72CPkSJgAQ8X6WwGHDr/06n/+4cfhRvJMsGvBfnshJm+cwEfS1VYRo2yQhqKdkL5m6M+6XlMtUQ4KgSGuNKHeUcoGZrsQ8q2kpJnVuIDcXtwz3xksg3Z2RheIfUjEhO9farSUWg4SqtiPth1EMTrr4wDM9viaId3GhpkqJYe0cfT+79d9POv1y4AH730v2LR0sEhLSNyyE10curXUvA+Jp28JOSi6T0BGJRMFTYizuGR6wkZjJhyzotTM4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: flask-creds
      namespace: projectblr

